id: P54604643
initial_creation_type: input
source_metadata:
  title: Aśvaghoṣa Series
  language: en
  description: 'Texts by and about the great Indian master Aśvaghoṣa (Tib. rta dbyangs):'
  volume:
    6abaca17dedb4a318d0bb662a5d025d8:
      title: Extremely Concise Dedication
      parent: Dedication
    68cbea7accde4343bb6b8103c2067772:
      title: Root Downfalls of the Vajra Vehicle
      parent: Samaya
    7cbe1093beeb4ac8b7ee744189495463:
      title: Summary of the Root Downfalls of the Vajra Vehicle
      parent: Samaya
created_at: '2022-03-01T02:09:56.156354'
last_modified_at: '2022-03-01T02:09:56.156360'
